#!/bin/bash
#
#   Copyright [2011] [Red Hat, Inc.]
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#  limitations under the License.
#

PROGNAME=`basename $0`
USAGE=$(cat <<END_OF_USAGE
  Usage: $0 UUID

    Generate a bare-bones instance-config.xml document based on the provided
    UUID.  The document is output to standard out.
END_OF_USAGE
)

UUID="$1"
if [ "x$UUID" == "x" ]; then
  echo "Please provide a value for UUID.  This can be any value."
  echo "$USAGE"
  exit 1
fi

XML=$(cat <<END_OF_XML
<instance-config id='$UUID' name='$UUID' type='$UUID'>
    <deployable name='$UUID' id='$UUID'/>
    <template name='$UUID'/>
</instance-config>
END_OF_XML
)

echo "$XML"
