#!/bin/bash

/usr/bin/thin start -c $CONFIG_SERVER_DIR -l $THIN_LOG \
  -P $THIN_PID -a $THIN_IP -e $RACK_ENV \
  --user $AEOLUS_USER --group $AEOLUS_GROUP \
  -d --prefix=${PREFIX} -R $CONFIG_SERVER_RACKUP -p $CONFIG_SERVER_PORT
