# -*- ruby -*-
# Rakefile: build aeolus config server
#
# Copyright (C) 2011 Red Hat, Inc.
#
# Distributed under the GNU Lesser General Public License v2.1 or later.
# See COPYING for details
#
# Greg Blomquist <gblomqui@redhat.com>

# Rakefile for ruby-rpm -*- ruby -*-
require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
# JJV rake/gempackagetask is deprecated.
# JJV require 'rubygems/package_task'

version = '0.4.1'
pkg_name = 'aeolus-configserver'

SPEC_FILE_IN="aeolus-configserver.spec.in"
SPEC_FILE="aeolus-configserver.spec"
CONFIG_RU="src/config.ru"
LOGS="log"

GENERATED_FILES=[
  [SPEC_FILE_IN,SPEC_FILE,false,nil],
  [CONFIG_RU,CONFIG_RU,true,nil]
]

#
# Package tasks
#

# This FileList explicitly excludes both the spec file and the config.ru
# files, since these both go through variable substitution in the RPM task
# below.  And, rake uses hard links to copy files into the package location,
# which would change both the packaged file and the file in the source tree.
configserver_files = FileList[
  "aeolus-configserver.spec.in",
  "Rakefile", "COPYING",
  "schema/*.rng",
  "src/**/*.*",
  "conf/*",
  "client/*",
  "configure/**/*",
].exclude(CONFIG_RU).exclude(SPEC_FILE).exclude(LOGS)

spec = Gem::Specification.new do |s|
  s.name = pkg_name
  s.version = version
  s.email = "aeolus-devel@fedorahosted.org"
  s.homepage = "http://aeolusproject.org"
  s.summary = "Aeolus Config Server"
  s.files = configserver_files
  s.required_ruby_version = '>= 1.8.1'
  s.author = "Greg Blomquist"
  s.rubyforge_project = "None"
  s.description = "Aeolus Config Server."
end

p = Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = true
  pkg.need_zip = false
end

# Allow for generated files
# In this case, we allow for files that replace the "@VERSION@" text with the
# actual package version.  Some generated files are packaged, while others are
# simply used during packaging.
GENERATED_FILES.each do |(source_file,dest_file,is_packaged,block)|
  # create the file task to generate the file
  if is_packaged
    packaged_name = "#{p.package_name}/#{source_file}"
    dependencies = [p.package_dir_path] + p.package_files
  else
    packaged_name = dest_file
    dependencies = [p.package_dir] + p.package_files
  end
  if block != nil
    block.call(source_file, packaged_name, dependencies, p)
  else
    puts "JJV packaged_name: #{packaged_name}"
    puts "JJV packaged_name: #{packaged_name}"
    puts "JJV packaged_name: #{packaged_name}"
    puts "JJV packaged_name: #{packaged_name}"
    puts "JJV packaged_name: #{packaged_name}"
    puts "JJV packaged_name: #{packaged_name}"
    puts "JJV source_file: #{source_file}"
    cmd = "sed -e 's/@VERSION@/#{version}/' #{source_file} " \
        "> #{p.package_dir}/#{packaged_name}"
    puts "JJV -010- cmd: #{cmd}"
    puts "JJV -010- cmd: #{cmd}"
    puts "JJV -010- cmd: #{cmd}"
    puts "JJV -010- cmd: #{cmd}"
    puts "JJV -010- cmd: #{cmd}"
    puts "JJV -010- cmd: #{cmd}"
    file "#{p.package_dir}/#{packaged_name}" => dependencies do
      puts "JJV -020- cmd: #{cmd}"
      puts "JJV -020- cmd: #{cmd}"
      puts "JJV -020- cmd: #{cmd}"
      puts "JJV -020- cmd: #{cmd}"
      puts "JJV -020- cmd: #{cmd}"
      puts "JJV -020- cmd: #{cmd}"
      puts "JJV -020- cmd: #{cmd}"
      system("#{cmd}")
    end
  end

  # make the zip/tar/etc. task depend on the created file task
  [
    [p.need_tar, p.tgz_file],
    [p.need_tar_gz, p.tar_gz_file],
    [p.need_tar_bz2, p.tar_bz2_file],
    [p.need_zip, p.zip_file]
  ].each do |(need, ar_file)|
    if need
      task "#{p.package_dir}/#{ar_file}" => ["#{p.package_dir}/#{packaged_name}"]
    end
  end
end

# Clean up the build destination
CLEAN.include('pkg')


# Build the (S)RPMs
desc "Build (S)RPMs for #{pkg_name}"
task :rpm => [ :package ] do |t|
  Dir::chdir("pkg") do |dir|
    dir = File::expand_path(".")
    system("which rpmbuild &> /dev/null")
    if $? != 0
      raise "No rpmbuild command found. Please install the " \
          "rpm-build package to run the rpm rake task."
    end
    # set pipefail so if rpmbuild fails, it's status is reported back
    # to the rake task
    cmd = "set -o pipefail && rpmbuild " \
          "--define '_sourcedir #{dir}' " \
          "-ba #{SPEC_FILE} | tee rpmbuild.log 2>&1"
    puts "Running: #{cmd}"
    system(cmd)
    rpmbuild_status = $?
    if rpmbuild_status != 0
      raise "rpmbuild failed (exit code: #{rpmbuild_status})"
    end
  end
end
