# -*- ruby -*-
# Rakefile: build aeolus config server
#
# Copyright (C) 2011 Red Hat, Inc.
#
# Distributed under the GNU Lesser General Public License v2.1 or later.
# See COPYING for details
#
# Greg Blomquist <gblomqui@redhat.com>

# Rakefile for ruby-rpm -*- ruby -*-
require 'rake/clean'
require 'rake/gempackagetask'

PKG_NAME='aeolus-configserver'
PKG_VERSION='0.0.2'

SPEC_FILE="aeolus-configserver.spec"

#
# Package tasks
#

PKG_FILES = FileList[
  "Rakefile", "COPYING",
  "schema/*.rng",
  "src/**/*.*",
  "conf/**/*",
]

DIST_FILES = FileList[
  "pkg/*.src.rpm",  "pkg/*.gem",  "pkg/*.zip", "pkg/*.tgz"
]

SPEC = Gem::Specification.new do |s|
    s.name = PKG_NAME
    s.version = PKG_VERSION
    s.email = "aeolus-devel@fedorahosted.org"
    s.homepage = "http://aeolusproject.org"
    s.summary = "Aeolus Config Server"
    s.files = PKG_FILES
    s.required_ruby_version = '>= 1.8.1'
    s.author = "Greg Blomquist"
    s.rubyforge_project = "None"
    s.description = "Aeolus Config Server."
end

Rake::GemPackageTask.new(SPEC) do |pkg|
    pkg.need_tar = true
    pkg.need_zip = true
end

desc "Build (S)RPM for #{PKG_NAME}"
task :rpm => [ :package ] do |t|
    system("sed -e 's/@VERSION@/#{PKG_VERSION}/' #{SPEC_FILE} > pkg/#{SPEC_FILE}")
    Dir::chdir("pkg") do |dir|
        dir = File::expand_path(".")
        system("which rpmbuild &> /dev/null")
        if $? != 0
            raise "Oops, no rpmbuild command found.  Please install the rpm-build package to run the rpm rake task."
        end
        system("rpmbuild --define '_topdir #{dir}' --define '_sourcedir #{dir}' --define '_srcrpmdir #{dir}' --define '_rpmdir #{dir}' --define '_builddir #{dir}' -ba #{SPEC_FILE} > rpmbuild.log 2>&1")
        if $? != 0
            raise "rpmbuild failed"
        end
    end
end
