#! /bin/sh

BASEDIR=$(dirname $0)

CAT=/bin/cat
NODES_DIR="${BASEDIR}/nodes"

# look for node setting files, or revert to default
[ -f ${NODES_DIR}/$1 ] && NODE=$1 || NODE=default

$CAT $NODES_DIR/$NODE
